name: CI Workflow 
on: [push, pull_request] 
jobs: 
  build: 
    runs-on: self-ubuntu-24.04
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 
      - name: Compile LaTeX document
        run: latexmk -pdf main.tex